# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investidea', models.CharField(max_length=51)),
                ('post', tinymce.models.HTMLField()),
                ('locationjpg', models.ImageField(upload_to='jpg/')),
            ],
        ),
    ]
