# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invekeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['investidea']},
        ),
        migrations.AddField(
            model_name='business',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
